// const jsonata = require('jsonata');

module.exports.getExpression = function(msg) {
  let body =  JSON.stringify(msg.body, undefined, 2);
  console.log(`MSG BODY: ${body}`);
  const expression = {
    "rowid": msg.body.applicationRecordUid,
    "name": msg.body.lastName,
    "first_name": msg.body.firstName,
    // "tenant": msg.body.tenant,
    // "for_rowid": msg.body.for_rowid,
    // "for_table": msg.body.for_table,
    // "department": msg.body.department,
    // "position": msg.body.position,
    // "phone2": msg.body.phone2,
    // "phone3": msg.body.phone3,
    // "standard_person": msg.body.standard_person,
    // "title": msg.body.title,
    // "name": msg.body.lastName,
    // "phone": msg.body.phone,
    "email": msg.body.email,
    // "fax": msg.body.fax,
    // "mobile_phone": msg.body.mobile_phone,
    // "remarks": msg.body.remarks,
    // "updated_by_user": msg.body.updated_by_user,
    // "updated_by_user_group": msg.body.updated_by_user_group,
    // "salutation": msg.body.salutation,
    // "serial_salutation": msg.body.serial_salutation,
    // "address_category1": msg.body.address_category1,
    // "address_category2": msg.body.address_category2,
    // "address_category3": msg.body.address_category3,
    // "address_category4": msg.body.address_category4,
    // "last_update": msg.body.applicatioLastModified,
    // "date_of_birth": msg.body.birthday,
    // "private_street": msg.body.private_street,
    // "private_zip_code": msg.body.private_zip_code,
    // "private_town": msg.body.private_town,
    // "import_key": msg.body.import_key,
    // "wp_contact_remote_addr": msg.body.wp_contact_remote_addr,
    // "deactivated": msg.body.deactivated,
    // "same_contactperson": msg.body.same_contactperson,
    // "house_post_code": msg.body.house_post_code,
    // "picture_url": msg.body.photo,
    // "xing_url": msg.body.xing_url,
    // "caring_employee": msg.body.caring_employee,
    // "private_street_number": msg.body.private_street_number,
    // "private_country": msg.body.private_country,
    // "private_country_symbol": msg.body.private_country_symbol,
    // "private_phone": msg.body.private_phone,
    // "private_mobile_phone": msg.body.private_mobile_phone,
    // "private_email": msg.body.private_email,
    // "created_by_wp_contact": msg.body.created_by_wp_contact,
    // "history_log": msg.body.history_log,
    // "eternal_exclusion_from_all_mailinglists": msg.body.eternal_exclusion_from_all_mailinglists,
    // "email_check_result": msg.body.email_check_result,
    // "do_not_display_anymore_in_duplicate_list_in_wp_contact": msg.body.do_not_display_anymore_in_duplicate_list_in_wp_contact,
    // "created_by_wp_wice_freemium_admin": msg.body.created_by_wp_wice_freemium_admin,
    // "address_category5": msg.body.address_category5,
    // "address_category6": msg.body.address_category6,
    // "address_category7": msg.body.address_category7,
    // "same_contactperson_top": msg.body.same_contactperson_top,
    // "facebook_url": msg.body.facebook_url,
    // "linked_in_url": msg.body.linked_in_url,
    // "twitter_url": msg.body.twitter_url,
    // "googleplus_url": msg.body.googleplus_url,
    // "usergroups_read": msg.body.usergroups_read,
    // "usergroups_write": msg.body.usergroups_write,
    // "is_private": msg.body.is_private,
    // "is_favourite": msg.body.is_favourite,
    // "skype": msg.body.skype,
    // "user_account_rowid": msg.body.user_account_rowid,
    // "is_deleted": msg.body.is_deleted,
    // "private_state": msg.body.private_state,
    // "youtube_url": msg.body.youtube_url,
    // "url": msg.body.url,
    // "company_name": msg.body.company_name,
    // "name_and_firstname": msg.body.name_and_firstname,
    // "total_entries_readable_with_current_permissions": msg.body.total_entries_readable_with_current_permissions
  };
  return expression;
}
